# Generated by Django 6.0.4 on 2026-04-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Main display image",
                null=True,
                upload_to="rooms/",
            ),
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="rooms/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="booking.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
